# Generated by Django 5.2.5 on 2025-09-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_session_key_alter_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='session_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
